### PR TITLE
Generic transaction handling

### PR DESCRIPTION
**Pull request by szerintedmi**
New shiny and generic way to handle  Ethereum transactions. 
- [`Transaction`](https://github.com/Augmint/augmint-js/blob/tx_reorg/src/Transaction.ts) class encapsulates all features to send Ethereum transactions. It handles the whole transaction lifecycle.
- No  web3.js implementation details are exposed from this class to the consumers so upgrading or changing it should be easier. (apart from the input which has to be a web3 transaction and return values such as receipt)
- you can chain method calls, eg. `tx.sign(..).send(..).getTxReceipt()`
- You can get a receipt after n  confirmations received: `await receipt = tx.send(...).getConfirmedReceipt(5)` 
- For backward compatibility it fires the same events (`transactionHash`, `confirmation`, `receipt`, `error`) as `web3.js` `PromiEvent` just these are working (tested with current web3.js beta36). E.g. you get receipt, transactionHash and confirmations for EVM reverted but mined transactions (consumers must check `receipt.status` and can get details from `tx.sendError`)

TODO: 
- tested only on ganche. rinkeby and mainnet tests are still required
- `getConfirmedReceipt` needs to reject after x blocks if not enough confirmation received (or after timeout)

## Breaking changes
- `Rates` and `Exchange` are using new methods to send transactions. `Ratesfeeder` and `MatchMaker` has to catch up
- launching ganache with `--noVMErrorsOnRPCResponse` flag. It emulates real chain behaviour better (i.e. tx receipt, hash and confirmations are still received even if EVM reverts). But not returning revert reasons currently so if you need that then launch ganache without the flag (one test will break)

### simple send
```js
const txReceipt = await rates
    .setRate(CCY, expectedPrice)
    .send({ from: accounts[0] })
    .getTxReceipt();
assert(txReceipt.status);
```
### simple sign & send

```js
const txReceipt = await rates
    .setRate(CCY, expectedPrice)
    .sign(PRIVATE_KEY, {
        from: accounts[0]
    })
    .send()
    .getTxReceipt();

assert(txReceipt.status);
```

### Fully fledged example
```js
const ethereumConnection = new EthereumConnection(config);
const rates = new Rates();

await rates.connect()
rates.setRate(CCY, rate)
       // optionally you can sign
       // .sign(privatekey, {from: acc, to:rates.address})]  
       .send([{from: acc}]) // {from: 0x} only needed if it's not signed
       .onceTxHash( txHash => {.. })
       .onceReceipt( receipt => { ...})
       .onConfirmation( (confirmationNumber, receipt) => {...}
       .onceReceiptConfirmed(5, receipt => {...})
       .onceTxRevert( (error, receipt) => { ....});

// To catch errors you need to use txHash / confirmation / receipt getters:
try {
    const txHash = await tx.getTxHash()
    const txReceipt = await tx.getReceipt() // receipt as soon as got it (even with 0 confirmation)
    const confirmedReceipt = await tx.getConfirmedReceipt(12) // receipt after x confirmation.
    // receipt you need to check for receipt.status if tx was Reverted or not.
    if (confirmedReceipt.status) {
      // all good
    } else {
      // this tx was reverted
    }
} catch (error) {
     // These Promises are rejecting with sending errors or when txhash / receipt times out.
 }
```
Specs: [test/Transaction.test.js](https://github.com/Augmint/augmint-js/blob/tx_reorg/test/Transaction.test.js)

### More examples
- [test/Rates.setters.test.js](https://github.com/Augmint/augmint-js/blob/tx_reorg/test/Rates.setters.test.js)
- [test/Exchange.Matching.onchain.test.js](https://github.com/Augmint/augmint-js/blob/tx_reorg/test/Exchange.Matching.onchain.test.js)

### Web3.js event style
 Deprecated and discouraged but kept for backward compatibility  with web3js style events:
```js
 tx.on[ce]("transactionHash" | "receipt" | "confirmation" | "error")
 // This way it can be easily plugged into dapps which are handling web3js tx objects:
 //   augmint-js Transaction object can be a drop in as an almost direct replacement of webjs transactioObject
```
Specs: [test/Transaction.web3jsStyle.test.js](https://github.com/Augmint/augmint-js/blob/tx_reorg/test/Transaction.web3jsStyle.test.js)

### Construct a transaction
It's likely not needed for ordinary `augmint-js` users
```js
 const web3TxObject = rates.instance.methods.setRate(CCY, 100)
 const augmintRatesTx = new Transaction(ethereumConnection, web3TxObject, {gasLimit: 200000}); // you can set the gaslimit here or later at send() too
 augmintRatesTx.send(...).onTxHash(...)  // or sign().send() etc.
```

### CODE REVIEW

**Comment by szerintedmi** [comment]
> I would omit the `on('error', fn)` etc event listener-style methods unless it's clear that the client code is better that way than with promises. Even if it's deemed necessary, I would suggest `onError(fn)` etc methods for compile-time safety.


I tried to follow web3 current conventions for easier adoption for anyone familiar with that. but it might not worth it.


it wouldn't be to much a pain to change it at this phase.

@rszaloki ?

**Comment by rszaloki** [comment]
the `on(string, callback)` is everywhere (not just in web3, but generally in javascript world), so I think we should go with that.

**Comment by szerintedmi** [comment]
My suggestion:
1. keep the `.on[ce](<"transactionHash" | "receipt" | "confrimation" | "error" >)` events. This is node standard event handling and web3js using these names, de-facto standard for dapp development.  It's much easier to plug in to existing infrastructure. Live example: [switch to augmint-js here](https://github.com/Augmint/augmint-web/pull/597/files#diff-2cc3a252a0186454401e463cec68f58c) - we didn't have to touch existing `processTx()`
Once we reworked the FE we can consider remove support for those event types or add stronger type safety to event names if it causes any issues. 
In general agree to discourage use of these events because of lack of type safety.

1. keep existing promise fns:  `.getTxHash()`,  `.getTxReceipt()`, `getTxConfirmation(<confnumber>)` (rename it to `getConfirmedReceipt(<confNumber>)`)

1. add type safe callback style fns such as: 
 - `onceTxHash(cb)`
 - `onceReceipt(cb)`
-  `onConfirmation(cb)`
 - `onceConfirmed(confrimationCount, cb)`
 - `onError(cb)`  (I couldn't figure if error could be called more than once...)  
  This would make it possible to write more flowing code of  
    ```
    tx
      .onceTxHash( {..})
      .onceReceipt({...)
    ...
    ```

**Comment by szerintedmi** [comment]
With latest set of commits.

### Recommended use:
```js
const ethereumConnection = new EthereumConnection(config);
const rates = new Rates();

await rates.connect()
rates.setRate
       // optionally you can sign
       // .sign(privatekey, {from: acc, to:rates.address})]  
       .send([{from: acc}]) // {from: 0x} only needed if it's not signed
       .onceTxHash( txHash => {.. })
       .onceReceipt( receipt => { ...})
       .onConfirmation( (confirmationNumber, receipt) => {...}
       .onceReceiptConfirmed(5, receipt => {...})
       .onceTxRevert( (error, receipt) => { ....})
       .catch(error => {
             // any error while signing/sending
        })

// Getting txHash / confirmation / receipt these promises can be also used:
try {
    const txHash = await tx.getTxHash()
    const txReceipt = await tx.getReceipt() // receipt as soon as got it (even with 0 confirmation)
    const confirmedReceipt = await tx.getConfirmedReceipt(12) // receipt after x confirmation.
    // receipt you need to check for receipt.status if tx was Reverted or not.
    if (confirmedReceipt.status) {
      // all good
    } else {
      // this tx was reverted
    }
} catch (error) {
     // These Promises are rejecting with sending errors or when txhash / receipt times out.
 }
```

###
 Deprecated and discouraged but kept for backward compatibility  with web3js style events:
```js
 tx.on[ce]("transactionHash" | "receipt" | "confirmation" | "error")]
 // This way it can be easily plugged into dapps which are handling web3js tx objects:
 //   augmint-js Transaction object can be a drop in as an almost direct replacement of webjs transactioObject
```

# Construct a transaction:
```js
 const web3TxObject = rates.instance.methods.setRate(CCY, 100)
 const augmintRatesTx = new Transaction(ethereumConnection, web3TxObject, {gasLimit: 200000}); // you can set the gaslimit here or later at send() too
 augmintRatesTx.send(...).onTxHash(...)  // or sign().send() etc.
```

**Pull request merged**
